[@@@ocaml.warning "-33"] (*-- TEMP: until we slowly wire in the logic that is generated by the bot by evaluating it carefully*)
(** [subroutines] unit-level tests for the core Paxos invariants.

    These tests exercise the pure logic in {!Node_state.Make_node_state}
    and {!Types} without spinning up a full simulation.  They are the
    cheapest tests to write and the fastest to run.

    Invariants under test:
    1. Quorum thresholds   — is_quorum_reached returns the right variant
    2. Proposal ordering   — is_proposal_permissible / is_suggestion_acceptable
*)

open Base
open Paxos


let%expect_test "hello world" =
  Stdio.print_string "paxos tests are alive" ;
  [%expect {| paxos tests are alive |}]
