(*-- TEMP: until we slowly wire in the logic that is generated by the bot by evaluating it carefully*)
(* [e2e] + [integration] scenario tests for the Paxos simulator.

    These tests spin up a headless {!Simulator.Simulator}, seed nodes, inject
    events, run to completion, and then assert on the resulting node states.

    Because they exercise the full message dispatch loop, they are the right
    place to verify cross-cutting properties like:
    - Safety: no two nodes ever decide differently
    - Liveness (conditional): if a majority can communicate, they decide

    --------------------------------------------------------------------
    NOTE on expect output:
    Run [dune runtest --auto-promote] once after first compilation to
    let ppx_expect capture the actual output and fill in the [%expect]
    blocks below.  After that, any regression is caught automatically.
    --------------------------------------------------------------------
*)

open! Base
open Paxos
module Sim = Simulator.Simulator

(*sanity check on the e2e test harness*)
let%expect_test
    "integration: simulator can be constructed and stepped without crashing" =
  let sim = Test_utils.make_silent_sim ~max_ticks:3 () in
  (* Run 3 ticks with no nodes; just confirm the machinery doesn't explode. *)
  Test_utils.run_to_completion sim ;
  Stdio.print_string "it doesn't blow up in our face" ;
  [%expect {| it doesn't blow up in our face |}]
