(lang dune 3.20)

(name paxos)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Ritesh Kumar <ritesh@emerald.pink>")

(maintainers "Ritesh Kumar <ritesh@emerald.pink>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name paxos)
 (synopsis "Learning paxos algo(s) using ocaml.")
 (description "A summary exercise at the end of a head-first dive into learning ocaml, this package just has some learning examples. ")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
