(lang dune 3.20)

(name paxos)

(generate_opam_files true)

(source
 (github rtshkmr/paxos_ocaml_demo))

(authors "Ritesh Kumar <hello@rtshkmr.com>")

(maintainers "Ritesh Kumar <hello@rtshkmr.com>")

(license GPL-3.0-only)

(package
 (name paxos)
 (synopsis "Learning paxos algo(s) using ocaml.")
 (description
  "A summary exercise at the end of a head-first dive into learning ocaml, this package just has some learning examples")
 (depends
  ocaml
  dune
  base
  stdio
  core
  core_unix
  yojson
  re
  ppx_deriving_yojson
  ppx_jane
  (ocaml-lsp-server :with-dev)
  (merlin :with-dev)
  (ocamlformat :with-dev)
  (utop :with-dev))
 (tags
  ("distributed" "consensus" "ocaml" "paxos" "learning")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
